# Generated by Django 5.0.7 on 2024-07-21 00:59

import tt_backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Readings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=tt_backend.models.get_default_date)),
                ('time', models.TimeField(default=tt_backend.models.get_default_time)),
                ('systolic', models.PositiveIntegerField()),
                ('diastolic', models.PositiveIntegerField()),
                ('pulse', models.PositiveIntegerField(blank=True, null=True)),
                ('oxygen', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
